@startuml aws_architecture
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/General/Internetalt1.puml
!include AWSPuml/NetworkingContentDelivery/VPC.puml
!include AWSPuml/NetworkingContentDelivery/VPCPublicSubnet.puml
!include AWSPuml/NetworkingContentDelivery/ElasticLoadBalancingApplicationLoadBalancer.puml
!include AWSPuml/Compute/EC2AutoScaling.puml
!include AWSPuml/Compute/EC2Instance.puml
!include AWSPuml/DeveloperTools/ToolsandSDKs.puml

title "AWS Jenkins + Docker Infrastructure (Terraform)"

rectangle "AWS Cloud" {
    VPC(vpc, "VPC\n(10.0.0.0/16)", "VPC") {
        
        rectangle "Availability Zone A (ap-south-1a)" {
            VPCPublicSubnet(subnet_1, "Public Subnet 1\n(10.0.1.0/24)", "Subnet") {
                EC2Instance(ec2_1, "EC2 (Docker + Jenkins)", "Instance")
            }
        }

        rectangle "Availability Zone B (ap-south-1b)" {
            VPCPublicSubnet(subnet_2, "Public Subnet 2\n(10.0.2.0/24)", "Subnet") {
                
            }
        }
        
        ElasticLoadBalancingApplicationLoadBalancer(alb, "Application Load Balancer\n(:80)", "ALB")
    }
}

Internetalt1(internet, "GitHub / Internet", "Web")
ToolsandSDKs(github, "Source Control", "GitHub")

internet --> alb : HTTP :80
alb --> ec2_1 : routes traffic
@enduml
